<a href="https://colab.research.google.com/github/ESJoGithub/PythonStudy/blob/main/Python_0805_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy 활용 예제 실습

#### **배열 만들기 및 초기화**

In [2]:
import numpy as np

In [7]:
data = np.array([1, 2, 3, 4, 5, 6])
data_2d = np.array([[1,2,3],[4,5,6]])
data_random = np.random.randn(2, 3) # 2X3 Matrinx
data_zeros = np.zeros(5)            # 1X5 Matrinx
data_ones = np.ones((2,3))          # 2X3 Matrinx

In [8]:
print(data)
print(data_2d)
print(data_random)
print(data_zeros)
print(data_ones)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[-1.3136338  -0.61082002 -1.30280424]
 [-0.35561087 -0.03976749  0.90995202]]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


#### **배열의 요소 추출**

In [9]:
data2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [10]:
print(data2)
print(data2[0][1])
print(data2[0][1:])
data2[0] = 100                      # for문을 사용하지 않아도 됨.
print(data2)
data2[:] = 300                      # for문을 사용하지 않아도 됨.
print(data2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[2 3]
[[100 100 100]
 [  4   5   6]
 [  7   8   9]]
[[300 300 300]
 [300 300 300]
 [300 300 300]]


#### **배열의 산술연산**

In [12]:
data_a = np.array([[5,7,9], [-7,-6,19],[6,8.9,11]])
data_b = data_a*2
data_c = data_a+3
print(data_a)
print(data_b)
print(data_c)
print(data_a > data_b)

[[ 5.   7.   9. ]
 [-7.  -6.  19. ]
 [ 6.   8.9 11. ]]
[[ 10.   14.   18. ]
 [-14.  -12.   38. ]
 [ 12.   17.8  22. ]]
[[ 8.  10.  12. ]
 [-4.  -3.  22. ]
 [ 9.  11.9 14. ]]
[[False False False]
 [ True  True False]
 [False False False]]


#### **배열의 통계 메소드**

In [15]:
print(data_a)
print(data_a.sum())
print(data_a.mean())
print(data_a.max())
print(data_a.min())
print(data_a.max(axis = 0))           # axis = 0 은 각 열별 데이터를 의미함 axis = 1은 행을 기준으로 함
index_1 = np.argmax(data_a, axis = 0) # 각 열에서 최대값을 가지는 인덱스 반환
print(index_1)

[[ 5.   7.   9. ]
 [-7.  -6.  19. ]
 [ 6.   8.9 11. ]]
52.9
5.877777777777777
19.0
-7.0
[ 9. 19. 11.]
[2 2 1]
